name: almasah_dates
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0       # for HTTP requests
  path_provider: ^2.0.5  # to get local storage paths
  open_filex: ^4.2.1  # to open files
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/darkGreenLogo.png